name: Build Changed Projects
run-name: ${{ github.event.inputs.pr_number }}

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read
  pull-requests: write

on:
  pull_request_target:
    types: [synchronize]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR Number (leave empty for main branch)'

jobs:
  build:
    runs-on: windows-11-arm
    steps:
      - name: Ensure this workflow has been triggered manually recently for this PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          if ("${{ github.event_name }}" -eq "pull_request_target") {
            $ONE_MONTH_AGO = (Get-Date).AddMonths(-1).ToString("yyyy-MM-dd")
            $RUN_NAMES = gh api "repos/${{ github.repository }}/actions/workflows/build_projects.yml/runs?event=workflow_dispatch&created=>=$ONE_MONTH_AGO" --jq '.workflow_runs[].display_title'
            if ($RUN_NAMES -notcontains "${{ github.event.pull_request.number }}") {
              Write-Host "Run this workflow manually - it hasn't been done recently"
              exit 1
            }
          }

      - name: Configure AWS credentials
        shell: pwsh
        run: |
          $OIDC_TOKEN = (Invoke-RestMethod -Uri "$env:ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" -Headers @{Authorization = "bearer $env:ACTIONS_ID_TOKEN_REQUEST_TOKEN"}).value
          
          $CREDENTIALS = aws sts assume-role-with-web-identity `
            --role-arn arn:aws:iam::236695143472:role/GitHubAction-AssumeRoleWithAction `
            --role-session-name "github-actions-${{ github.run_id }}" `
            --web-identity-token "$OIDC_TOKEN" `
            --duration-seconds 3600 `
            --query 'Credentials' `
            --output json | ConvertFrom-Json
          
          "AWS_ACCESS_KEY_ID=$($CREDENTIALS.AccessKeyId)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "AWS_SECRET_ACCESS_KEY=$($CREDENTIALS.SecretAccessKey)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "AWS_SESSION_TOKEN=$($CREDENTIALS.SessionToken)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "AWS_DEFAULT_REGION=eu-central-1" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install Pipeline Package
        shell: pwsh
        run: |
          git clone https://x-token-auth:${{ secrets.STARTER_MODELS_PIPELINE_TOKEN }}@bitbucket.org/imagimob/_starter-projects-pipeline.git
          pip install -e _starter-projects-pipeline

      - name: Build changed projects
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ("${{ github.event_name }}" -eq "pull_request_target") {
            $PR_NUMBER = "${{ github.event.pull_request.number }}"
          } elseif ("${{ github.event_name }}" -eq "workflow_dispatch") {
            $PR_NUMBER = "${{ github.event.inputs.pr_number }}"
          }
          update-changes --pr-number "$PR_NUMBER"
