name: Build and Deploy Changed Projects from main

permissions:
  id-token: write
  contents: write

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [deploy_main]

jobs:
  deploy:
    runs-on: windows-11-arm
    steps:
      - name: Configure AWS credentials
        shell: pwsh
        run: |
          $OIDC_TOKEN = (Invoke-RestMethod -Uri "$env:ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" -Headers @{Authorization = "bearer $env:ACTIONS_ID_TOKEN_REQUEST_TOKEN"}).value
          
          $CREDENTIALS = aws sts assume-role-with-web-identity `
            --role-arn arn:aws:iam::236695143472:role/GitHubAction-AssumeRoleWithAction `
            --role-session-name "github-actions-${{ github.run_id }}" `
            --web-identity-token "$OIDC_TOKEN" `
            --duration-seconds 3600 `
            --query 'Credentials' `
            --output json | ConvertFrom-Json
          
          "AWS_ACCESS_KEY_ID=$($CREDENTIALS.AccessKeyId)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "AWS_SECRET_ACCESS_KEY=$($CREDENTIALS.SecretAccessKey)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "AWS_SESSION_TOKEN=$($CREDENTIALS.SessionToken)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "AWS_DEFAULT_REGION=eu-central-1" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install Pipeline Package
        shell: pwsh
        run: |
          git clone https://x-token-auth:${{ secrets.STARTER_MODELS_PIPELINE_TOKEN }}@bitbucket.org/imagimob/_starter-projects-pipeline.git
          pip install -e _starter-projects-pipeline

      - name: Build and deploy (if needed) changed projects
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          update-changes
