name: PR - Build Changed Projects
run-name: >
  ${{
    github.event_name == 'workflow_dispatch' && github.event.inputs.pr_number ||
    github.event_name == 'repository_dispatch' && github.event.client_payload.pr_number ||
    ''
  }}

permissions:
  id-token: write
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR Number'
        required: true
  pull_request_target:
    types: [synchronize]
  repository_dispatch:
    types: [pr_build]

jobs:
  build:
    runs-on: windows-11-arm
    steps:
      - name: Ensure recent manual trigger
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          if ("${{ github.event_name }}" -eq "pull_request_target") {
            $ONE_MONTH_AGO = (Get-Date).AddMonths(-1).ToString("yyyy-MM-dd")
            $RUN_NAMES = gh api "repos/${{ github.repository }}/actions/workflows/build_projects.yml/runs?event=workflow_dispatch&created=>=$ONE_MONTH_AGO" --jq '.workflow_runs[].display_title'
            if ($RUN_NAMES -notcontains "${{ github.event.pull_request.number }}") {
              Write-Host "Run this workflow manually - it hasn't been done recently"
              exit 1
            }
          }

      - name: Install Pipeline Package
        shell: pwsh
        run: |
          git clone https://x-token-auth:${{ secrets.STARTER_MODELS_PIPELINE_TOKEN }}@bitbucket.org/imagimob/_starter-projects-pipeline.git
          pip install -e _starter-projects-pipeline

      - name: Build changed projects
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $JOB_ID = ""
          if ("${{ github.event_name }}" -eq "workflow_dispatch") {
            $PR_NUMBER = "${{ github.event.inputs.pr_number }}"
          } elseif ("${{ github.event_name }}" -eq "pull_request_target") {
            $PR_NUMBER = "${{ github.event.pull_request.number }}"
          } elseif ("${{ github.event_name }}" -eq "repository_dispatch") {
            $PR_NUMBER = "${{ github.event.client_payload.pr_number }}"
            $JOB_ID = "--job-id ${{ github.event.client_payload.job_id }}"
          } else {
            throw "Unsupported event: ${{ github.event_name }}"
          }
          update-changes --pr-number "$PR_NUMBER" $JOB_ID
