name: PR - Build Changed Projects
run-name: ${{ github.event.inputs.pr_number }}

permissions:
  id-token: write
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR Number'
        required: true
  pull_request_target:
    types: [synchronize]
  repository_dispatch:
    types: [build_pr]

jobs:
  build:
    runs-on: windows-11-arm
    steps:
      - name: Ensure this workflow has been triggered manually recently for this PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          if ("${{ github.event_name }}" -eq "pull_request_target") {
            $ONE_MONTH_AGO = (Get-Date).AddMonths(-1).ToString("yyyy-MM-dd")
            $RUN_NAMES = gh api "repos/${{ github.repository }}/actions/workflows/build_projects.yml/runs?event=workflow_dispatch&created=>=$ONE_MONTH_AGO" --jq '.workflow_runs[].display_title'
            if ($RUN_NAMES -notcontains "${{ github.event.pull_request.number }}") {
              Write-Host "Run this workflow manually - it hasn't been done recently"
              exit 1
            }
          }

      - name: Install Pipeline Package
        shell: pwsh
        run: |
          git clone https://x-token-auth:${{ secrets.STARTER_MODELS_PIPELINE_TOKEN }}@bitbucket.org/imagimob/_starter-projects-pipeline.git
          pip install -e _starter-projects-pipeline

      - name: Build changed projects
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ("${{ github.event_name }}" -eq "pull_request_target") {
            $PR_NUMBER = "${{ github.event.pull_request.number }}"
          } else {
            $PR_NUMBER = "${{ github.event.inputs.pr_number }}"
          }
          update-changes --pr-number "$PR_NUMBER"
