name: Update ECR PW

on:
  # Disable cron until we start using aws ecr
  # schedule:
    # Token is valid for 12 hours, so update it every 11 hours
    # - cron: 02 */11 * * *
  workflow_dispatch:

jobs:
  update-ecr-pw:
    runs-on: windows-11-arm
    permissions:
      id-token: write
      contents: read
    env:
      GH_TOKEN: ${{ secrets.GH_CLI }}
    steps:
      - name: Configure AWS credentials
        shell: pwsh
        run: |
          $OIDC_TOKEN = (Invoke-RestMethod -Uri "$env:ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" -Headers @{Authorization = "bearer $env:ACTIONS_ID_TOKEN_REQUEST_TOKEN"}).value
          
          $CREDENTIALS = aws sts assume-role-with-web-identity `
            --role-arn arn:aws:iam::236695143472:role/GitHubAction-AssumeRoleWithAction `
            --role-session-name "github-actions-${{ github.run_id }}" `
            --web-identity-token "$OIDC_TOKEN" `
            --duration-seconds 3600 `
            --query 'Credentials' `
            --output json | ConvertFrom-Json
          
          "AWS_ACCESS_KEY_ID=$($CREDENTIALS.AccessKeyId)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "AWS_SECRET_ACCESS_KEY=$($CREDENTIALS.SecretAccessKey)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "AWS_SESSION_TOKEN=$($CREDENTIALS.SessionToken)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "AWS_DEFAULT_REGION=eu-central-1" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Get pw and update secret
        run: |
          $AWS_ECR_PW = "aws ecr get-login-password --region eu-central-1 --output text"
          gh secret set AWS_ECR_PW --repo ${{ github.repository }} --body "$AWS_ECR_PW"
